import { Dimensions, StyleSheet } from 'react-native';
const { width, height } = Dimensions.get('screen');
export default styles = StyleSheet.create({
   containerView: {
      flex: 1,
      backgroundColor: '#ffffff',
   },
   footer: {
      backgroundColor: '#ffffff',
      height: 150,
      justifyContent: 'center',
      paddingVertical: 5,
      borderRadius: 10,
   },
   map: {
      height: '100%',
      marginTop: 0,
   },
   searchBoxView: {
      flexDirection: 'row',
      backgroundColor: 'white',
      backgroundColor: 'black',
      width: '90%',
      minHeight: 50,
      marginTop: 12,
      // paddingHorizontal: 8,
      borderWidth: 1,
      borderRadius: 5,
   },
   searchIcon: {
      color: '#42A5F5',
      marginTop: 12,
      marginLeft: 10,
   },
   searchBox: {
      alignSelf: 'stretch',
      fontSize: 17,
      width: '100%',
   },
   pickupImage: {
      marginLeft: 8,
      marginTop: 10,
      width: 25,
      height: 25,
   },
   DoneButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#42A5F1',
      height: 50,
      width: 350,
      marginTop: 5,
      marginLeft: 3,
   },
   destinationContainer: {
      width: '100%',
      alignItems: 'center',
      paddingVertical: 5,
   },
   destinationTextContainer: {
      width: '100%',
      alignItems: 'flex-start',
      paddingHorizontal: 20,
   },
   destnationText: {
      fontSize: 18,
      fontWeight: 'bold',
   },
   headerContainer: {
      backgroundColor: '#fff',
      height: 50,
   },
   headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
   },
   drawerButton: {
      zIndex: 2,
      position: 'absolute',
      top: 40,
      left: 20,
      fontSize: 20,
   },
   tripContainer: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
   },
   type: {
      width: '30%',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
   },
   priceRange: {
      width: '40%',
      justifyContent: 'center',
      alignItems: 'center',
   },
   typeTitle: {
      fontSize: 17,
      fontWeight: 'bold',
   },
   typeTime: {
      color: 'grey',
   },
   pricing: {
      fontSize: 15,
      fontWeight: 'bold',
   },
   closeButton: {
      marginTop: 5,
      fontSize: 30,
   },
   closeButtonContainer: {
      borderStartColor: 'red',
      alignSelf: 'flex-end',
   },
   modelContainer: {
      backgroundColor: '#2B2B2B',
      width: '100%',
      height: '50%',
      paddingTop: 20,
      paddingVertical: 8,
   },
   modelHeader: {
      width: '100%',
      height: 300,
      backgroundColor: '#2B2B2B',
      alignSelf: 'flex-end',
   },
   modelFooter: {
      width: '100%',
      height: 100,
      backgroundColor: '#2B2B2B',
      alignSelf: 'flex-end',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
   },
   acceptButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#1b1b1b',
      width: '30%',
      height: 45,
      marginTop: 15,
      marginHorizontal: 8,
      borderRadius: 8,
   },
   cancelButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#1b1b1b',
      width: '30%',
      height: 45,
      marginTop: 15,
      marginHorizontal: 8,
      borderRadius: 8,
   },
   acceptText: {
      color: '#ffffff',
      fontWeight: 'bold',
   },
   cancelText: {
      color: '#ffffff',
      fontWeight: 'bold',
   },
   image: {
      width: '22%',
      height: '100%',
      backgroundColor: '#D3D3D3',
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
   },
   imageContainer: {
      width: '100%',
      height: 80,
      justifyContent: 'center',
      alignItems: 'center',
   },
   driverName: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
   },
   driverDetailsContainer: {
      width: '100%',
      height: 80,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#2B2B2B',
   },
   raiting: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
   },
   raitingContainer: {
      width: '100%',
      height: 80,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#2B2B2B',
   },
   nameText: {
      fontSize: 19,
      color: 'white',
      fontWeight: 'bold',
   },
   mapContainer: {
      width: '100%',
      height: '100%',
      alignSelf: 'center',
      justifyContent: 'center',
   },
   bookButton: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
   },
   bookButtonContainer: {
      width: '100%',
      height: 50,
      borderRadius: 5,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#2B2B2B',
      flexDirection: 'column',
   },
   bookText: { color: 'white' },
   bottomSheetContainer: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: '#1A1A1A',
      paddingBottom: 50,
   },
   bottomSheetHeader: {
      width,
      paddingHorizontal: 7,
      marginVertical: 3,
   },
   carsList: {
      marginTop: 50,
      position: 'relative',
      width,
   },
   container: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 4,
      backgroundColor: 'black',
      height: 50,
      width: '100%',
   },
   leftContainer: {
      flex: 1,
      // paddingLeft: 10,
   },
   text: {
      fontSize: 18,
      color: 'white',
   },
   iconContainer: {
      paddingHorizontal: 10,
   },
   arrowIconContainer: {
      paddingRight: 10,
   },

   button: {
      backgroundColor: '#333',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 5,
      elevation: 5,
   },
   buttonText: {
      color: 'white',
      fontSize: 18,
   },
   modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)', // Fundo semi-transparente
   },
   modalContent: {
      padding: 20,
      borderRadius: 10,
   },
   modalText: {
      fontSize: 18,
      marginBottom: 20,
   },
   modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
   },
   modalButton: {
      backgroundColor: '#333',
      padding: 10,
      borderRadius: 5,
      width: '45%',
      alignItems: 'center',
   },
   modalButtonText: {
      color: 'white',
      fontSize: 16,
   },
});
